//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CamaraContext : DbContext
    {
        public CamaraContext()
            : base("name=CamaraContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Entidad> sp_Entidad_sel(string cODENT, string nOMENT)
        {
            var cODENTParameter = cODENT != null ?
                new ObjectParameter("CODENT", cODENT) :
                new ObjectParameter("CODENT", typeof(string));
    
            var nOMENTParameter = nOMENT != null ?
                new ObjectParameter("NOMENT", nOMENT) :
                new ObjectParameter("NOMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Entidad>("sp_Entidad_sel", cODENTParameter, nOMENTParameter);
        }
    
        public virtual ObjectResult<Morcam> sp_Morcam_sel(Nullable<double> nUDOCA, string aPNOCA, string eMPRCA)
        {
            var nUDOCAParameter = nUDOCA.HasValue ?
                new ObjectParameter("NUDOCA", nUDOCA) :
                new ObjectParameter("NUDOCA", typeof(double));
    
            var aPNOCAParameter = aPNOCA != null ?
                new ObjectParameter("APNOCA", aPNOCA) :
                new ObjectParameter("APNOCA", typeof(string));
    
            var eMPRCAParameter = eMPRCA != null ?
                new ObjectParameter("EMPRCA", eMPRCA) :
                new ObjectParameter("EMPRCA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Morcam>("sp_Morcam_sel", nUDOCAParameter, aPNOCAParameter, eMPRCAParameter);
        }
    
        public virtual ObjectResult<MorosoEnCamara> sp_ObtenerMorosoEnCamara(Nullable<double> nUDOCA, string aPNOCA)
        {
            var nUDOCAParameter = nUDOCA.HasValue ?
                new ObjectParameter("NUDOCA", nUDOCA) :
                new ObjectParameter("NUDOCA", typeof(double));
    
            var aPNOCAParameter = aPNOCA != null ?
                new ObjectParameter("APNOCA", aPNOCA) :
                new ObjectParameter("APNOCA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MorosoEnCamara>("sp_ObtenerMorosoEnCamara", nUDOCAParameter, aPNOCAParameter);
        }
    
        public virtual ObjectResult<MI_RegistrosPorFila_Result> MI_RegistrosPorFila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MI_RegistrosPorFila_Result>("MI_RegistrosPorFila");
        }
    }
}
