//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int CDocumento { get; set; }
        public string Cnombre { get; set; }
        public string CCodDocu { get; set; }
        public string Cdomicilio { get; set; }
        public string CCodPost { get; set; }
        public string Clocalidad { get; set; }
        public string CProvincia { get; set; }
        public string CTelefono1 { get; set; }
        public string CTelefono2 { get; set; }
        public string CComplemento { get; set; }
        public Nullable<System.DateTime> CFechaNaci { get; set; }
        public string CNombCony { get; set; }
        public Nullable<int> CDocuCony { get; set; }
        public string CCodDocuCony { get; set; }
        public string CEmpresa { get; set; }
        public string CDomicilioE { get; set; }
        public string CCodPostE { get; set; }
        public string CLocalidadE { get; set; }
        public string CProvinciaE { get; set; }
        public string CTelefonoE { get; set; }
        public string CComplementoE { get; set; }
        public Nullable<decimal> CSueldo { get; set; }
        public string CCodEmpleo { get; set; }
        public string CComLab { get; set; }
        public string CCodLegal { get; set; }
        public string CSexo { get; set; }
        public string CPremium { get; set; }
        public Nullable<int> CPuntaje { get; set; }
        public string CNotas { get; set; }
        public string CCod1 { get; set; }
        public string CCod2 { get; set; }
        public Nullable<double> CNumCod { get; set; }
        public string CAvisado { get; set; }
        public bool ModP { get; set; }
        public bool ModL { get; set; }
        public string Conocio { get; set; }
        public bool Veraz { get; set; }
        public string QueEs { get; set; }
        public Nullable<double> cnumcli { get; set; }
        public Nullable<int> COmercio { get; set; }
        public string Legajo { get; set; }
        public Nullable<byte> etique { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> FechV { get; set; }
        public Nullable<int> Comer { get; set; }
        public Nullable<System.DateTime> fetiq { get; set; }
        public Nullable<System.DateTime> fMModi { get; set; }
        public Nullable<int> CodCobr { get; set; }
        public Nullable<System.DateTime> fCobr { get; set; }
        public string Zona { get; set; }
    }
}
