//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobranzasANT
    {
        public short AComercio { get; set; }
        public int ACredito { get; set; }
        public byte ANumCuota { get; set; }
        public string ADigVeri { get; set; }
        public Nullable<decimal> AImpPago { get; set; }
        public Nullable<decimal> AImpPuni { get; set; }
        public Nullable<decimal> AImpInte { get; set; }
        public Nullable<System.DateTime> AFechaPago { get; set; }
        public Nullable<System.DateTime> AHoraPago { get; set; }
        public Nullable<decimal> APuniCalc { get; set; }
        public Nullable<int> ALote { get; set; }
        public Nullable<System.DateTime> AFechLote { get; set; }
        public Nullable<System.DateTime> AFechPro { get; set; }
        public string APago { get; set; }
        public Nullable<decimal> AImpPagoAnt { get; set; }
        public Nullable<System.DateTime> AFechPagoAnt { get; set; }
        public Nullable<decimal> AImpPuniAnt { get; set; }
        public bool APagoRev { get; set; }
        public Nullable<System.DateTime> AFechaRev { get; set; }
        public bool ABonificado { get; set; }
        public double ANumCob { get; set; }
        public string ADeta { get; set; }
        public Nullable<short> AGestion { get; set; }
        public string Usuario { get; set; }
        public bool Cancela { get; set; }
        public Nullable<double> NumeDia { get; set; }
        public Nullable<int> NumRef { get; set; }
        public Nullable<System.DateTime> AFechVenci { get; set; }
        public string ACobra { get; set; }
        public string PcPro { get; set; }
        public string UsuarioPro { get; set; }
        public string TipoBoni { get; set; }
        public Nullable<decimal> PorBoni { get; set; }
    }
}
