//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(iComercio.DAL.ComerFinanEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets993646a45171057d220becd0c1deb674fbcd4e6851252cb76994504e588fced8))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySets993646a45171057d220becd0c1deb674fbcd4e6851252cb76994504e588fced8 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "993646a45171057d220becd0c1deb674fbcd4e6851252cb76994504e588fced8"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "ComerFinanModelStoreContainer.Bajas")
            {
                return GetView0();
            }

            if (extentName == "ComerFinanEntities.Bajas")
            {
                return GetView1();
            }

            if (extentName == "ComerFinanModelStoreContainer.Clientes")
            {
                return GetView2();
            }

            if (extentName == "ComerFinanEntities.Clientes")
            {
                return GetView3();
            }

            if (extentName == "ComerFinanModelStoreContainer.Cobranzas")
            {
                return GetView4();
            }

            if (extentName == "ComerFinanEntities.ANT")
            {
                return GetView5();
            }

            if (extentName == "ComerFinanModelStoreContainer.Creditos")
            {
                return GetView6();
            }

            if (extentName == "ComerFinanEntities.CreditosANT")
            {
                return GetView7();
            }

            if (extentName == "ComerFinanModelStoreContainer.Cuotas")
            {
                return GetView8();
            }

            if (extentName == "ComerFinanEntities.CuotasANT")
            {
                return GetView9();
            }

            if (extentName == "ComerFinanModelStoreContainer.Notas")
            {
                return GetView10();
            }

            if (extentName == "ComerFinanEntities.Notas")
            {
                return GetView11();
            }

            if (extentName == "ComerFinanModelStoreContainer.RefiBaja")
            {
                return GetView12();
            }

            if (extentName == "ComerFinanEntities.RefiBaja")
            {
                return GetView13();
            }

            if (extentName == "ComerFinanModelStoreContainer.Reficobra")
            {
                return GetView14();
            }

            if (extentName == "ComerFinanEntities.RefiCobra")
            {
                return GetView15();
            }

            if (extentName == "ComerFinanModelStoreContainer.RefiCuotas")
            {
                return GetView16();
            }

            if (extentName == "ComerFinanEntities.RefiCuotas")
            {
                return GetView17();
            }

            if (extentName == "ComerFinanModelStoreContainer.Refinan")
            {
                return GetView18();
            }

            if (extentName == "ComerFinanEntities.Refinan")
            {
                return GetView19();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Bajas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Bajas
        [ComerFinanModel.Store.Bajas](T1.Bajas_KComercio, T1.Bajas_KCredito, T1.Bajas_KDocumento, T1.Bajas_KCodDocu, T1.Bajas_KValorNom, T1.Bajas_KValorCuota, T1.Bajas_KFechSoli, T1.Bajas_KFechCorte, T1.Bajas_KFechPrese, T1.Bajas_KFechProce, T1.Bajas_KLote, T1.Bajas_KOrden, T1.Bajas_KOrdenBaja, T1.Bajas_KLoteBaja, T1.Bajas_KInteresImp, T1.Bajas_KGastoImp, T1.Bajas_KComisionImp, T1.Bajas_KAvalado, T1.Bajas_KAbogado, T1.Bajas_KCancelado, T1.Bajas_KGarante1, T1.Bajas_KCodDocuG1, T1.Bajas_KGarante2, T1.Bajas_KCodDocuG2, T1.Bajas_KGarante3, T1.Bajas_KCodDocuG3, T1.Bajas_KVtopp, T1.Bajas_KCodPlan, T1.Bajas_KTipCuota, T1.Bajas_KCuotas, T1.Bajas_KTasa, T1.Bajas_KGasto, T1.Bajas_KPeriodi, T1.Bajas_KRetencion, T1.Bajas_KPremiun, T1.Bajas_KEfectivo, T1.Bajas_KBonifica, T1.Bajas_KPlazo, T1.Bajas_KComision, T1.Bajas_KVenci, T1.Bajas_KCorte1, T1.Bajas_KCorte2, T1.Bajas_KVenDia1, T1.Bajas_KVenDia2, T1.Bajas_KVenDia3, T1.Bajas_KNotas, T1.Bajas_KCausa, T1.Bajas_Usuario, T1.Bajas_KFechaLote, T1.Bajas_VaM)
    FROM (
        SELECT 
            T.KComercio AS Bajas_KComercio, 
            T.KCredito AS Bajas_KCredito, 
            T.KDocumento AS Bajas_KDocumento, 
            T.KCodDocu AS Bajas_KCodDocu, 
            T.KValorNom AS Bajas_KValorNom, 
            T.KValorCuota AS Bajas_KValorCuota, 
            T.KFechSoli AS Bajas_KFechSoli, 
            T.KFechCorte AS Bajas_KFechCorte, 
            T.KFechPrese AS Bajas_KFechPrese, 
            T.KFechProce AS Bajas_KFechProce, 
            T.KLote AS Bajas_KLote, 
            T.KOrden AS Bajas_KOrden, 
            T.KOrdenBaja AS Bajas_KOrdenBaja, 
            T.KLoteBaja AS Bajas_KLoteBaja, 
            T.KInteresImp AS Bajas_KInteresImp, 
            T.KGastoImp AS Bajas_KGastoImp, 
            T.KComisionImp AS Bajas_KComisionImp, 
            T.KAvalado AS Bajas_KAvalado, 
            T.KAbogado AS Bajas_KAbogado, 
            T.KCancelado AS Bajas_KCancelado, 
            T.KGarante1 AS Bajas_KGarante1, 
            T.KCodDocuG1 AS Bajas_KCodDocuG1, 
            T.KGarante2 AS Bajas_KGarante2, 
            T.KCodDocuG2 AS Bajas_KCodDocuG2, 
            T.KGarante3 AS Bajas_KGarante3, 
            T.KCodDocuG3 AS Bajas_KCodDocuG3, 
            T.KVtopp AS Bajas_KVtopp, 
            T.KCodPlan AS Bajas_KCodPlan, 
            T.KTipCuota AS Bajas_KTipCuota, 
            T.KCuotas AS Bajas_KCuotas, 
            T.KTasa AS Bajas_KTasa, 
            T.KGasto AS Bajas_KGasto, 
            T.KPeriodi AS Bajas_KPeriodi, 
            T.KRetencion AS Bajas_KRetencion, 
            T.KPremiun AS Bajas_KPremiun, 
            T.KEfectivo AS Bajas_KEfectivo, 
            T.KBonifica AS Bajas_KBonifica, 
            T.KPlazo AS Bajas_KPlazo, 
            T.KComision AS Bajas_KComision, 
            T.KVenci AS Bajas_KVenci, 
            T.KCorte1 AS Bajas_KCorte1, 
            T.KCorte2 AS Bajas_KCorte2, 
            T.KVenDia1 AS Bajas_KVenDia1, 
            T.KVenDia2 AS Bajas_KVenDia2, 
            T.KVenDia3 AS Bajas_KVenDia3, 
            T.KNotas AS Bajas_KNotas, 
            T.KCausa AS Bajas_KCausa, 
            T.Usuario AS Bajas_Usuario, 
            T.KFechaLote AS Bajas_KFechaLote, 
            T.VaM AS Bajas_VaM, 
            True AS _from0
        FROM ComerFinanEntities.Bajas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.Bajas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Bajas
        [ComerFinanModel.Bajas](T1.Bajas_KComercio, T1.Bajas_KCredito, T1.Bajas_KDocumento, T1.Bajas_KCodDocu, T1.Bajas_KValorNom, T1.Bajas_KValorCuota, T1.Bajas_KFechSoli, T1.Bajas_KFechCorte, T1.Bajas_KFechPrese, T1.Bajas_KFechProce, T1.Bajas_KLote, T1.Bajas_KOrden, T1.Bajas_KOrdenBaja, T1.Bajas_KLoteBaja, T1.Bajas_KInteresImp, T1.Bajas_KGastoImp, T1.Bajas_KComisionImp, T1.Bajas_KAvalado, T1.Bajas_KAbogado, T1.Bajas_KCancelado, T1.Bajas_KGarante1, T1.Bajas_KCodDocuG1, T1.Bajas_KGarante2, T1.Bajas_KCodDocuG2, T1.Bajas_KGarante3, T1.Bajas_KCodDocuG3, T1.Bajas_KVtopp, T1.Bajas_KCodPlan, T1.Bajas_KTipCuota, T1.Bajas_KCuotas, T1.Bajas_KTasa, T1.Bajas_KGasto, T1.Bajas_KPeriodi, T1.Bajas_KRetencion, T1.Bajas_KPremiun, T1.Bajas_KEfectivo, T1.Bajas_KBonifica, T1.Bajas_KPlazo, T1.Bajas_KComision, T1.Bajas_KVenci, T1.Bajas_KCorte1, T1.Bajas_KCorte2, T1.Bajas_KVenDia1, T1.Bajas_KVenDia2, T1.Bajas_KVenDia3, T1.Bajas_KNotas, T1.Bajas_KCausa, T1.Bajas_Usuario, T1.Bajas_KFechaLote, T1.Bajas_VaM)
    FROM (
        SELECT 
            T.KComercio AS Bajas_KComercio, 
            T.KCredito AS Bajas_KCredito, 
            T.KDocumento AS Bajas_KDocumento, 
            T.KCodDocu AS Bajas_KCodDocu, 
            T.KValorNom AS Bajas_KValorNom, 
            T.KValorCuota AS Bajas_KValorCuota, 
            T.KFechSoli AS Bajas_KFechSoli, 
            T.KFechCorte AS Bajas_KFechCorte, 
            T.KFechPrese AS Bajas_KFechPrese, 
            T.KFechProce AS Bajas_KFechProce, 
            T.KLote AS Bajas_KLote, 
            T.KOrden AS Bajas_KOrden, 
            T.KOrdenBaja AS Bajas_KOrdenBaja, 
            T.KLoteBaja AS Bajas_KLoteBaja, 
            T.KInteresImp AS Bajas_KInteresImp, 
            T.KGastoImp AS Bajas_KGastoImp, 
            T.KComisionImp AS Bajas_KComisionImp, 
            T.KAvalado AS Bajas_KAvalado, 
            T.KAbogado AS Bajas_KAbogado, 
            T.KCancelado AS Bajas_KCancelado, 
            T.KGarante1 AS Bajas_KGarante1, 
            T.KCodDocuG1 AS Bajas_KCodDocuG1, 
            T.KGarante2 AS Bajas_KGarante2, 
            T.KCodDocuG2 AS Bajas_KCodDocuG2, 
            T.KGarante3 AS Bajas_KGarante3, 
            T.KCodDocuG3 AS Bajas_KCodDocuG3, 
            T.KVtopp AS Bajas_KVtopp, 
            T.KCodPlan AS Bajas_KCodPlan, 
            T.KTipCuota AS Bajas_KTipCuota, 
            T.KCuotas AS Bajas_KCuotas, 
            T.KTasa AS Bajas_KTasa, 
            T.KGasto AS Bajas_KGasto, 
            T.KPeriodi AS Bajas_KPeriodi, 
            T.KRetencion AS Bajas_KRetencion, 
            T.KPremiun AS Bajas_KPremiun, 
            T.KEfectivo AS Bajas_KEfectivo, 
            T.KBonifica AS Bajas_KBonifica, 
            T.KPlazo AS Bajas_KPlazo, 
            T.KComision AS Bajas_KComision, 
            T.KVenci AS Bajas_KVenci, 
            T.KCorte1 AS Bajas_KCorte1, 
            T.KCorte2 AS Bajas_KCorte2, 
            T.KVenDia1 AS Bajas_KVenDia1, 
            T.KVenDia2 AS Bajas_KVenDia2, 
            T.KVenDia3 AS Bajas_KVenDia3, 
            T.KNotas AS Bajas_KNotas, 
            T.KCausa AS Bajas_KCausa, 
            T.Usuario AS Bajas_Usuario, 
            T.KFechaLote AS Bajas_KFechaLote, 
            T.VaM AS Bajas_VaM, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Bajas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Clientes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Clientes
        [ComerFinanModel.Store.Clientes](T1.Clientes_CDocumento, T1.Clientes_CCodDocu, T1.Clientes_Cnombre, T1.Clientes_Cdomicilio, T1.Clientes_CCodPost, T1.Clientes_Clocalidad, T1.Clientes_CProvincia, T1.Clientes_CTelefono1, T1.Clientes_CTelefono2, T1.Clientes_CComplemento, T1.Clientes_CFechaNaci, T1.Clientes_CEmpresa, T1.Clientes_CDomicilioE, T1.Clientes_CCodPostE, T1.Clientes_CLocalidadE, T1.Clientes_CProvinciaE, T1.Clientes_CTelefonoE, T1.Clientes_CComplementoE, T1.Clientes_CSueldo, T1.Clientes_CCodEmpleo, T1.Clientes_CComLab, T1.Clientes_CCodLegal, T1.Clientes_CSexo, T1.Clientes_CPremium, T1.Clientes_CPuntaje, T1.Clientes_CNotas, T1.Clientes_CCod1, T1.Clientes_CCod2, T1.Clientes_CNumCod, T1.Clientes_CAvisado, T1.Clientes_ModP, T1.Clientes_ModL, T1.Clientes_Conocio, T1.Clientes_Veraz, T1.Clientes_QueEs, T1.Clientes_Legajo, T1.Clientes_CNumCli, T1.Clientes_CNombCony, T1.Clientes_CDocuCony, T1.Clientes_CCodDocuCony, T1.Clientes_COmercio, T1.Clientes_fechv, T1.Clientes_etique, T1.Clientes_mail, T1.Clientes_comer, T1.Clientes_fetiq, T1.Clientes_fMModi, T1.Clientes_CodCobr, T1.Clientes_fCobr, T1.Clientes_Zona)
    FROM (
        SELECT 
            T.CDocumento AS Clientes_CDocumento, 
            T.CCodDocu AS Clientes_CCodDocu, 
            T.Cnombre AS Clientes_Cnombre, 
            T.Cdomicilio AS Clientes_Cdomicilio, 
            T.CCodPost AS Clientes_CCodPost, 
            T.Clocalidad AS Clientes_Clocalidad, 
            T.CProvincia AS Clientes_CProvincia, 
            T.CTelefono1 AS Clientes_CTelefono1, 
            T.CTelefono2 AS Clientes_CTelefono2, 
            T.CComplemento AS Clientes_CComplemento, 
            T.CFechaNaci AS Clientes_CFechaNaci, 
            T.CEmpresa AS Clientes_CEmpresa, 
            T.CDomicilioE AS Clientes_CDomicilioE, 
            T.CCodPostE AS Clientes_CCodPostE, 
            T.CLocalidadE AS Clientes_CLocalidadE, 
            T.CProvinciaE AS Clientes_CProvinciaE, 
            T.CTelefonoE AS Clientes_CTelefonoE, 
            T.CComplementoE AS Clientes_CComplementoE, 
            T.CSueldo AS Clientes_CSueldo, 
            T.CCodEmpleo AS Clientes_CCodEmpleo, 
            T.CComLab AS Clientes_CComLab, 
            T.CCodLegal AS Clientes_CCodLegal, 
            T.CSexo AS Clientes_CSexo, 
            T.CPremium AS Clientes_CPremium, 
            T.CPuntaje AS Clientes_CPuntaje, 
            T.CNotas AS Clientes_CNotas, 
            T.CCod1 AS Clientes_CCod1, 
            T.CCod2 AS Clientes_CCod2, 
            T.CNumCod AS Clientes_CNumCod, 
            T.CAvisado AS Clientes_CAvisado, 
            T.ModP AS Clientes_ModP, 
            T.ModL AS Clientes_ModL, 
            T.Conocio AS Clientes_Conocio, 
            T.Veraz AS Clientes_Veraz, 
            T.QueEs AS Clientes_QueEs, 
            T.Legajo AS Clientes_Legajo, 
            T.CNumCli AS Clientes_CNumCli, 
            T.CNombCony AS Clientes_CNombCony, 
            T.CDocuCony AS Clientes_CDocuCony, 
            T.CCodDocuCony AS Clientes_CCodDocuCony, 
            T.COmercio AS Clientes_COmercio, 
            T.fechv AS Clientes_fechv, 
            T.etique AS Clientes_etique, 
            T.mail AS Clientes_mail, 
            T.comer AS Clientes_comer, 
            T.fetiq AS Clientes_fetiq, 
            T.fMModi AS Clientes_fMModi, 
            T.CodCobr AS Clientes_CodCobr, 
            T.fCobr AS Clientes_fCobr, 
            T.Zona AS Clientes_Zona, 
            True AS _from0
        FROM ComerFinanEntities.Clientes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.Clientes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Clientes
        [ComerFinanModel.Clientes](T1.Clientes_CDocumento, T1.Clientes_CCodDocu, T1.Clientes_Cnombre, T1.Clientes_Cdomicilio, T1.Clientes_CCodPost, T1.Clientes_Clocalidad, T1.Clientes_CProvincia, T1.Clientes_CTelefono1, T1.Clientes_CTelefono2, T1.Clientes_CComplemento, T1.Clientes_CFechaNaci, T1.Clientes_CEmpresa, T1.Clientes_CDomicilioE, T1.Clientes_CCodPostE, T1.Clientes_CLocalidadE, T1.Clientes_CProvinciaE, T1.Clientes_CTelefonoE, T1.Clientes_CComplementoE, T1.Clientes_CSueldo, T1.Clientes_CCodEmpleo, T1.Clientes_CComLab, T1.Clientes_CCodLegal, T1.Clientes_CSexo, T1.Clientes_CPremium, T1.Clientes_CPuntaje, T1.Clientes_CNotas, T1.Clientes_CCod1, T1.Clientes_CCod2, T1.Clientes_CNumCod, T1.Clientes_CAvisado, T1.Clientes_ModP, T1.Clientes_ModL, T1.Clientes_Conocio, T1.Clientes_Veraz, T1.Clientes_QueEs, T1.Clientes_Legajo, T1.Clientes_CNumCli, T1.Clientes_CNombCony, T1.Clientes_CDocuCony, T1.Clientes_CCodDocuCony, T1.Clientes_COmercio, T1.Clientes_fechv, T1.Clientes_etique, T1.Clientes_mail, T1.Clientes_comer, T1.Clientes_fetiq, T1.Clientes_fMModi, T1.Clientes_CodCobr, T1.Clientes_fCobr, T1.Clientes_Zona)
    FROM (
        SELECT 
            T.CDocumento AS Clientes_CDocumento, 
            T.CCodDocu AS Clientes_CCodDocu, 
            T.Cnombre AS Clientes_Cnombre, 
            T.Cdomicilio AS Clientes_Cdomicilio, 
            T.CCodPost AS Clientes_CCodPost, 
            T.Clocalidad AS Clientes_Clocalidad, 
            T.CProvincia AS Clientes_CProvincia, 
            T.CTelefono1 AS Clientes_CTelefono1, 
            T.CTelefono2 AS Clientes_CTelefono2, 
            T.CComplemento AS Clientes_CComplemento, 
            T.CFechaNaci AS Clientes_CFechaNaci, 
            T.CEmpresa AS Clientes_CEmpresa, 
            T.CDomicilioE AS Clientes_CDomicilioE, 
            T.CCodPostE AS Clientes_CCodPostE, 
            T.CLocalidadE AS Clientes_CLocalidadE, 
            T.CProvinciaE AS Clientes_CProvinciaE, 
            T.CTelefonoE AS Clientes_CTelefonoE, 
            T.CComplementoE AS Clientes_CComplementoE, 
            T.CSueldo AS Clientes_CSueldo, 
            T.CCodEmpleo AS Clientes_CCodEmpleo, 
            T.CComLab AS Clientes_CComLab, 
            T.CCodLegal AS Clientes_CCodLegal, 
            T.CSexo AS Clientes_CSexo, 
            T.CPremium AS Clientes_CPremium, 
            T.CPuntaje AS Clientes_CPuntaje, 
            T.CNotas AS Clientes_CNotas, 
            T.CCod1 AS Clientes_CCod1, 
            T.CCod2 AS Clientes_CCod2, 
            T.CNumCod AS Clientes_CNumCod, 
            T.CAvisado AS Clientes_CAvisado, 
            T.ModP AS Clientes_ModP, 
            T.ModL AS Clientes_ModL, 
            T.Conocio AS Clientes_Conocio, 
            T.Veraz AS Clientes_Veraz, 
            T.QueEs AS Clientes_QueEs, 
            T.Legajo AS Clientes_Legajo, 
            T.CNumCli AS Clientes_CNumCli, 
            T.CNombCony AS Clientes_CNombCony, 
            T.CDocuCony AS Clientes_CDocuCony, 
            T.CCodDocuCony AS Clientes_CCodDocuCony, 
            T.COmercio AS Clientes_COmercio, 
            T.fechv AS Clientes_fechv, 
            T.etique AS Clientes_etique, 
            T.mail AS Clientes_mail, 
            T.comer AS Clientes_comer, 
            T.fetiq AS Clientes_fetiq, 
            T.fMModi AS Clientes_fMModi, 
            T.CodCobr AS Clientes_CodCobr, 
            T.fCobr AS Clientes_fCobr, 
            T.Zona AS Clientes_Zona, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Clientes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Cobranzas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Cobranzas
        [ComerFinanModel.Store.Cobranzas](T1.Cobranzas_ACobra, T1.Cobranzas_AComercio, T1.Cobranzas_ACredito, T1.Cobranzas_ANumCuota, T1.Cobranzas_ANumCob, T1.Cobranzas_ADigVeri, T1.Cobranzas_AImpPago, T1.Cobranzas_AImpPuni, T1.Cobranzas_AImpInte, T1.Cobranzas_AFechaPago, T1.Cobranzas_AHoraPago, T1.Cobranzas_APuniCalc, T1.Cobranzas_ALote, T1.Cobranzas_AFechLote, T1.Cobranzas_AFechPro, T1.Cobranzas_APago, T1.Cobranzas_AImpPagoAnt, T1.Cobranzas_AFechPagoAnt, T1.Cobranzas_AImpPuniAnt, T1.Cobranzas_APagoRev, T1.Cobranzas_AFechaRev, T1.Cobranzas_ABonificado, T1.Cobranzas_ADeta, T1.Cobranzas_NumRef, T1.Cobranzas_AFechVenci, T1.Cobranzas_AGestion, T1.Cobranzas_Usuario, T1.Cobranzas_Cancela, T1.Cobranzas_UsuarioPro, T1.Cobranzas_NumeDia, T1.Cobranzas_TipoBoni, T1.Cobranzas_PorBoni, T1.Cobranzas_VaM, T1.[Cobranzas.PC_comer])
    FROM (
        SELECT 
            T.ACobra AS Cobranzas_ACobra, 
            T.AComercio AS Cobranzas_AComercio, 
            T.ACredito AS Cobranzas_ACredito, 
            T.ANumCuota AS Cobranzas_ANumCuota, 
            T.ANumCob AS Cobranzas_ANumCob, 
            T.ADigVeri AS Cobranzas_ADigVeri, 
            T.AImpPago AS Cobranzas_AImpPago, 
            T.AImpPuni AS Cobranzas_AImpPuni, 
            T.AImpInte AS Cobranzas_AImpInte, 
            T.AFechaPago AS Cobranzas_AFechaPago, 
            T.AHoraPago AS Cobranzas_AHoraPago, 
            T.APuniCalc AS Cobranzas_APuniCalc, 
            T.ALote AS Cobranzas_ALote, 
            T.AFechLote AS Cobranzas_AFechLote, 
            T.AFechPro AS Cobranzas_AFechPro, 
            T.APago AS Cobranzas_APago, 
            T.AImpPagoAnt AS Cobranzas_AImpPagoAnt, 
            T.AFechPagoAnt AS Cobranzas_AFechPagoAnt, 
            T.AImpPuniAnt AS Cobranzas_AImpPuniAnt, 
            T.APagoRev AS Cobranzas_APagoRev, 
            T.AFechaRev AS Cobranzas_AFechaRev, 
            T.ABonificado AS Cobranzas_ABonificado, 
            T.ADeta AS Cobranzas_ADeta, 
            T.NumRef AS Cobranzas_NumRef, 
            T.AFechVenci AS Cobranzas_AFechVenci, 
            T.AGestion AS Cobranzas_AGestion, 
            T.Usuario AS Cobranzas_Usuario, 
            T.Cancela AS Cobranzas_Cancela, 
            T.UsuarioPro AS Cobranzas_UsuarioPro, 
            T.NumeDia AS Cobranzas_NumeDia, 
            T.TipoBoni AS Cobranzas_TipoBoni, 
            T.PorBoni AS Cobranzas_PorBoni, 
            T.VaM AS Cobranzas_VaM, 
            T.PC_comer AS [Cobranzas.PC_comer], 
            True AS _from0
        FROM ComerFinanEntities.ANT AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.ANT.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ANT
        [ComerFinanModel.CobranzasANT](T1.CobranzasANT_ACobra, T1.CobranzasANT_AComercio, T1.CobranzasANT_ACredito, T1.CobranzasANT_ANumCuota, T1.CobranzasANT_ANumCob, T1.CobranzasANT_ADigVeri, T1.CobranzasANT_AImpPago, T1.CobranzasANT_AImpPuni, T1.CobranzasANT_AImpInte, T1.CobranzasANT_AFechaPago, T1.CobranzasANT_AHoraPago, T1.CobranzasANT_APuniCalc, T1.CobranzasANT_ALote, T1.CobranzasANT_AFechLote, T1.CobranzasANT_AFechPro, T1.CobranzasANT_APago, T1.CobranzasANT_AImpPagoAnt, T1.CobranzasANT_AFechPagoAnt, T1.CobranzasANT_AImpPuniAnt, T1.CobranzasANT_APagoRev, T1.CobranzasANT_AFechaRev, T1.CobranzasANT_ABonificado, T1.CobranzasANT_ADeta, T1.CobranzasANT_NumRef, T1.CobranzasANT_AFechVenci, T1.CobranzasANT_AGestion, T1.CobranzasANT_Usuario, T1.CobranzasANT_Cancela, T1.CobranzasANT_UsuarioPro, T1.CobranzasANT_NumeDia, T1.CobranzasANT_TipoBoni, T1.CobranzasANT_PorBoni, T1.CobranzasANT_VaM, T1.[CobranzasANT.PC_comer])
    FROM (
        SELECT 
            T.ACobra AS CobranzasANT_ACobra, 
            T.AComercio AS CobranzasANT_AComercio, 
            T.ACredito AS CobranzasANT_ACredito, 
            T.ANumCuota AS CobranzasANT_ANumCuota, 
            T.ANumCob AS CobranzasANT_ANumCob, 
            T.ADigVeri AS CobranzasANT_ADigVeri, 
            T.AImpPago AS CobranzasANT_AImpPago, 
            T.AImpPuni AS CobranzasANT_AImpPuni, 
            T.AImpInte AS CobranzasANT_AImpInte, 
            T.AFechaPago AS CobranzasANT_AFechaPago, 
            T.AHoraPago AS CobranzasANT_AHoraPago, 
            T.APuniCalc AS CobranzasANT_APuniCalc, 
            T.ALote AS CobranzasANT_ALote, 
            T.AFechLote AS CobranzasANT_AFechLote, 
            T.AFechPro AS CobranzasANT_AFechPro, 
            T.APago AS CobranzasANT_APago, 
            T.AImpPagoAnt AS CobranzasANT_AImpPagoAnt, 
            T.AFechPagoAnt AS CobranzasANT_AFechPagoAnt, 
            T.AImpPuniAnt AS CobranzasANT_AImpPuniAnt, 
            T.APagoRev AS CobranzasANT_APagoRev, 
            T.AFechaRev AS CobranzasANT_AFechaRev, 
            T.ABonificado AS CobranzasANT_ABonificado, 
            T.ADeta AS CobranzasANT_ADeta, 
            T.NumRef AS CobranzasANT_NumRef, 
            T.AFechVenci AS CobranzasANT_AFechVenci, 
            T.AGestion AS CobranzasANT_AGestion, 
            T.Usuario AS CobranzasANT_Usuario, 
            T.Cancela AS CobranzasANT_Cancela, 
            T.UsuarioPro AS CobranzasANT_UsuarioPro, 
            T.NumeDia AS CobranzasANT_NumeDia, 
            T.TipoBoni AS CobranzasANT_TipoBoni, 
            T.PorBoni AS CobranzasANT_PorBoni, 
            T.VaM AS CobranzasANT_VaM, 
            T.PC_comer AS [CobranzasANT.PC_comer], 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Cobranzas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Creditos.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Creditos
        [ComerFinanModel.Store.Creditos](T1.Creditos_KComercio, T1.Creditos_KCredito, T1.Creditos_KDocumento, T1.Creditos_KCodDocu, T1.Creditos_KValorNom, T1.Creditos_KValorCuota, T1.Creditos_KFechSoli, T1.Creditos_KFechCorte, T1.Creditos_KFechPrese, T1.Creditos_KFechProce, T1.Creditos_KLote, T1.Creditos_KNumExtra, T1.Creditos_KFechaLote, T1.Creditos_KOrden, T1.Creditos_KInteresImp, T1.Creditos_KGastoImp, T1.Creditos_KComisionImp, T1.Creditos_KAvalado, T1.Creditos_KCancelado, T1.Creditos_CodAdi, T1.Creditos_DocuAdi, T1.Creditos_KGarante1, T1.Creditos_KCodDocuG1, T1.Creditos_KGarante2, T1.Creditos_KCodDocuG2, T1.Creditos_KGarante3, T1.Creditos_KCodDocuG3, T1.Creditos_KVtopp, T1.Creditos_KCodPlan, T1.Creditos_KTipCuota, T1.Creditos_KCuotas, T1.Creditos_KTasa, T1.Creditos_KGasto, T1.Creditos_KPeriodi, T1.Creditos_KRetencion, T1.Creditos_KPremiun, T1.Creditos_KEfectivo, T1.Creditos_KBonifica, T1.Creditos_KPlazo, T1.Creditos_KComision, T1.Creditos_KVenci, T1.Creditos_KCorte1, T1.Creditos_KCorte2, T1.Creditos_KVenDia1, T1.Creditos_KVenDia2, T1.Creditos_KVenDia3, T1.Creditos_KNotas, T1.Creditos_KAbogado, T1.Creditos_kFechaAbo, T1.Creditos_FechaAbo, T1.Creditos_Refinan, T1.Creditos_Veraz, T1.Creditos_Usuario, T1.Creditos_QueAvalo, T1.Creditos_Carta1, T1.Creditos_FechaC1, T1.Creditos_Carta2, T1.Creditos_FechaC2, T1.Creditos_Carta3, T1.Creditos_FechaC3, T1.Creditos_Carta4, T1.Creditos_FechaC4, T1.Creditos_kempl, T1.Creditos_NroInf, T1.Creditos_UsuAval, T1.Creditos_TipoBoni, T1.Creditos_PorBoni, T1.Creditos_krmpl, T1.Creditos_Receptoria, T1.Creditos_VaM, T1.[Creditos.PC_comer], T1.[Creditos.hora_comer])
    FROM (
        SELECT 
            T.KComercio AS Creditos_KComercio, 
            T.KCredito AS Creditos_KCredito, 
            T.KDocumento AS Creditos_KDocumento, 
            T.KCodDocu AS Creditos_KCodDocu, 
            T.KValorNom AS Creditos_KValorNom, 
            T.KValorCuota AS Creditos_KValorCuota, 
            T.KFechSoli AS Creditos_KFechSoli, 
            T.KFechCorte AS Creditos_KFechCorte, 
            T.KFechPrese AS Creditos_KFechPrese, 
            T.KFechProce AS Creditos_KFechProce, 
            T.KLote AS Creditos_KLote, 
            T.KNumExtra AS Creditos_KNumExtra, 
            T.KFechaLote AS Creditos_KFechaLote, 
            T.KOrden AS Creditos_KOrden, 
            T.KInteresImp AS Creditos_KInteresImp, 
            T.KGastoImp AS Creditos_KGastoImp, 
            T.KComisionImp AS Creditos_KComisionImp, 
            T.KAvalado AS Creditos_KAvalado, 
            T.KCancelado AS Creditos_KCancelado, 
            T.CodAdi AS Creditos_CodAdi, 
            T.DocuAdi AS Creditos_DocuAdi, 
            T.KGarante1 AS Creditos_KGarante1, 
            T.KCodDocuG1 AS Creditos_KCodDocuG1, 
            T.KGarante2 AS Creditos_KGarante2, 
            T.KCodDocuG2 AS Creditos_KCodDocuG2, 
            T.KGarante3 AS Creditos_KGarante3, 
            T.KCodDocuG3 AS Creditos_KCodDocuG3, 
            T.KVtopp AS Creditos_KVtopp, 
            T.KCodPlan AS Creditos_KCodPlan, 
            T.KTipCuota AS Creditos_KTipCuota, 
            T.KCuotas AS Creditos_KCuotas, 
            T.KTasa AS Creditos_KTasa, 
            T.KGasto AS Creditos_KGasto, 
            T.KPeriodi AS Creditos_KPeriodi, 
            T.KRetencion AS Creditos_KRetencion, 
            T.KPremiun AS Creditos_KPremiun, 
            T.KEfectivo AS Creditos_KEfectivo, 
            T.KBonifica AS Creditos_KBonifica, 
            T.KPlazo AS Creditos_KPlazo, 
            T.KComision AS Creditos_KComision, 
            T.KVenci AS Creditos_KVenci, 
            T.KCorte1 AS Creditos_KCorte1, 
            T.KCorte2 AS Creditos_KCorte2, 
            T.KVenDia1 AS Creditos_KVenDia1, 
            T.KVenDia2 AS Creditos_KVenDia2, 
            T.KVenDia3 AS Creditos_KVenDia3, 
            T.KNotas AS Creditos_KNotas, 
            T.KAbogado AS Creditos_KAbogado, 
            T.kFechaAbo AS Creditos_kFechaAbo, 
            T.FechaAbo AS Creditos_FechaAbo, 
            T.Refinan AS Creditos_Refinan, 
            T.Veraz AS Creditos_Veraz, 
            T.Usuario AS Creditos_Usuario, 
            T.QueAvalo AS Creditos_QueAvalo, 
            T.Carta1 AS Creditos_Carta1, 
            T.FechaC1 AS Creditos_FechaC1, 
            T.Carta2 AS Creditos_Carta2, 
            T.FechaC2 AS Creditos_FechaC2, 
            T.Carta3 AS Creditos_Carta3, 
            T.FechaC3 AS Creditos_FechaC3, 
            T.Carta4 AS Creditos_Carta4, 
            T.FechaC4 AS Creditos_FechaC4, 
            T.kempl AS Creditos_kempl, 
            T.NroInf AS Creditos_NroInf, 
            T.UsuAval AS Creditos_UsuAval, 
            T.TipoBoni AS Creditos_TipoBoni, 
            T.PorBoni AS Creditos_PorBoni, 
            T.krmpl AS Creditos_krmpl, 
            T.Receptoria AS Creditos_Receptoria, 
            T.VaM AS Creditos_VaM, 
            T.PC_comer AS [Creditos.PC_comer], 
            T.hora_comer AS [Creditos.hora_comer], 
            True AS _from0
        FROM ComerFinanEntities.CreditosANT AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.CreditosANT.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CreditosANT
        [ComerFinanModel.CreditosANT](T1.CreditosANT_KComercio, T1.CreditosANT_KCredito, T1.CreditosANT_KDocumento, T1.CreditosANT_KCodDocu, T1.CreditosANT_KValorNom, T1.CreditosANT_KValorCuota, T1.CreditosANT_KFechSoli, T1.CreditosANT_KFechCorte, T1.CreditosANT_KFechPrese, T1.CreditosANT_KFechProce, T1.CreditosANT_KLote, T1.CreditosANT_KNumExtra, T1.CreditosANT_KFechaLote, T1.CreditosANT_KOrden, T1.CreditosANT_KInteresImp, T1.CreditosANT_KGastoImp, T1.CreditosANT_KComisionImp, T1.CreditosANT_KAvalado, T1.CreditosANT_KCancelado, T1.CreditosANT_CodAdi, T1.CreditosANT_DocuAdi, T1.CreditosANT_KGarante1, T1.CreditosANT_KCodDocuG1, T1.CreditosANT_KGarante2, T1.CreditosANT_KCodDocuG2, T1.CreditosANT_KGarante3, T1.CreditosANT_KCodDocuG3, T1.CreditosANT_KVtopp, T1.CreditosANT_KCodPlan, T1.CreditosANT_KTipCuota, T1.CreditosANT_KCuotas, T1.CreditosANT_KTasa, T1.CreditosANT_KGasto, T1.CreditosANT_KPeriodi, T1.CreditosANT_KRetencion, T1.CreditosANT_KPremiun, T1.CreditosANT_KEfectivo, T1.CreditosANT_KBonifica, T1.CreditosANT_KPlazo, T1.CreditosANT_KComision, T1.CreditosANT_KVenci, T1.CreditosANT_KCorte1, T1.CreditosANT_KCorte2, T1.CreditosANT_KVenDia1, T1.CreditosANT_KVenDia2, T1.CreditosANT_KVenDia3, T1.CreditosANT_KNotas, T1.CreditosANT_KAbogado, T1.CreditosANT_kFechaAbo, T1.CreditosANT_FechaAbo, T1.CreditosANT_Refinan, T1.CreditosANT_Veraz, T1.CreditosANT_Usuario, T1.CreditosANT_QueAvalo, T1.CreditosANT_Carta1, T1.CreditosANT_FechaC1, T1.CreditosANT_Carta2, T1.CreditosANT_FechaC2, T1.CreditosANT_Carta3, T1.CreditosANT_FechaC3, T1.CreditosANT_Carta4, T1.CreditosANT_FechaC4, T1.CreditosANT_kempl, T1.CreditosANT_NroInf, T1.CreditosANT_UsuAval, T1.CreditosANT_TipoBoni, T1.CreditosANT_PorBoni, T1.CreditosANT_krmpl, T1.CreditosANT_Receptoria, T1.CreditosANT_VaM, T1.[CreditosANT.PC_comer], T1.[CreditosANT.hora_comer])
    FROM (
        SELECT 
            T.KComercio AS CreditosANT_KComercio, 
            T.KCredito AS CreditosANT_KCredito, 
            T.KDocumento AS CreditosANT_KDocumento, 
            T.KCodDocu AS CreditosANT_KCodDocu, 
            T.KValorNom AS CreditosANT_KValorNom, 
            T.KValorCuota AS CreditosANT_KValorCuota, 
            T.KFechSoli AS CreditosANT_KFechSoli, 
            T.KFechCorte AS CreditosANT_KFechCorte, 
            T.KFechPrese AS CreditosANT_KFechPrese, 
            T.KFechProce AS CreditosANT_KFechProce, 
            T.KLote AS CreditosANT_KLote, 
            T.KNumExtra AS CreditosANT_KNumExtra, 
            T.KFechaLote AS CreditosANT_KFechaLote, 
            T.KOrden AS CreditosANT_KOrden, 
            T.KInteresImp AS CreditosANT_KInteresImp, 
            T.KGastoImp AS CreditosANT_KGastoImp, 
            T.KComisionImp AS CreditosANT_KComisionImp, 
            T.KAvalado AS CreditosANT_KAvalado, 
            T.KCancelado AS CreditosANT_KCancelado, 
            T.CodAdi AS CreditosANT_CodAdi, 
            T.DocuAdi AS CreditosANT_DocuAdi, 
            T.KGarante1 AS CreditosANT_KGarante1, 
            T.KCodDocuG1 AS CreditosANT_KCodDocuG1, 
            T.KGarante2 AS CreditosANT_KGarante2, 
            T.KCodDocuG2 AS CreditosANT_KCodDocuG2, 
            T.KGarante3 AS CreditosANT_KGarante3, 
            T.KCodDocuG3 AS CreditosANT_KCodDocuG3, 
            T.KVtopp AS CreditosANT_KVtopp, 
            T.KCodPlan AS CreditosANT_KCodPlan, 
            T.KTipCuota AS CreditosANT_KTipCuota, 
            T.KCuotas AS CreditosANT_KCuotas, 
            T.KTasa AS CreditosANT_KTasa, 
            T.KGasto AS CreditosANT_KGasto, 
            T.KPeriodi AS CreditosANT_KPeriodi, 
            T.KRetencion AS CreditosANT_KRetencion, 
            T.KPremiun AS CreditosANT_KPremiun, 
            T.KEfectivo AS CreditosANT_KEfectivo, 
            T.KBonifica AS CreditosANT_KBonifica, 
            T.KPlazo AS CreditosANT_KPlazo, 
            T.KComision AS CreditosANT_KComision, 
            T.KVenci AS CreditosANT_KVenci, 
            T.KCorte1 AS CreditosANT_KCorte1, 
            T.KCorte2 AS CreditosANT_KCorte2, 
            T.KVenDia1 AS CreditosANT_KVenDia1, 
            T.KVenDia2 AS CreditosANT_KVenDia2, 
            T.KVenDia3 AS CreditosANT_KVenDia3, 
            T.KNotas AS CreditosANT_KNotas, 
            T.KAbogado AS CreditosANT_KAbogado, 
            T.kFechaAbo AS CreditosANT_kFechaAbo, 
            T.FechaAbo AS CreditosANT_FechaAbo, 
            T.Refinan AS CreditosANT_Refinan, 
            T.Veraz AS CreditosANT_Veraz, 
            T.Usuario AS CreditosANT_Usuario, 
            T.QueAvalo AS CreditosANT_QueAvalo, 
            T.Carta1 AS CreditosANT_Carta1, 
            T.FechaC1 AS CreditosANT_FechaC1, 
            T.Carta2 AS CreditosANT_Carta2, 
            T.FechaC2 AS CreditosANT_FechaC2, 
            T.Carta3 AS CreditosANT_Carta3, 
            T.FechaC3 AS CreditosANT_FechaC3, 
            T.Carta4 AS CreditosANT_Carta4, 
            T.FechaC4 AS CreditosANT_FechaC4, 
            T.kempl AS CreditosANT_kempl, 
            T.NroInf AS CreditosANT_NroInf, 
            T.UsuAval AS CreditosANT_UsuAval, 
            T.TipoBoni AS CreditosANT_TipoBoni, 
            T.PorBoni AS CreditosANT_PorBoni, 
            T.krmpl AS CreditosANT_krmpl, 
            T.Receptoria AS CreditosANT_Receptoria, 
            T.VaM AS CreditosANT_VaM, 
            T.PC_comer AS [CreditosANT.PC_comer], 
            T.hora_comer AS [CreditosANT.hora_comer], 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Creditos AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Cuotas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Cuotas
        [ComerFinanModel.Store.Cuotas](T1.Cuotas_JComercio, T1.Cuotas_JCredito, T1.Cuotas_JNumCuota, T1.Cuotas_jdigveri, T1.Cuotas_JImpCuota, T1.Cuotas_JIntCuota, T1.Cuotas_JImpPago, T1.Cuotas_JImpPuni, T1.Cuotas_JFechUlti, T1.Cuotas_JFechVenci, T1.Cuotas_Jtipo, T1.Cuotas_JCantCuota, T1.Cuotas_JGestion, T1.Cuotas_JFechGest, T1.Cuotas_JCarta1, T1.Cuotas_JFechaC1, T1.Cuotas_JCarta2, T1.Cuotas_JFechaC2, T1.Cuotas_JCarta3, T1.Cuotas_JFechaC3, T1.Cuotas_JCarta4, T1.Cuotas_JFechaC4, T1.Cuotas_JBonificado, T1.Cuotas_jnotas, T1.Cuotas_JBonicado, T1.Cuotas_TipoBoni, T1.Cuotas_PorBoni, T1.Cuotas_VaM)
    FROM (
        SELECT 
            T.JComercio AS Cuotas_JComercio, 
            T.JCredito AS Cuotas_JCredito, 
            T.JNumCuota AS Cuotas_JNumCuota, 
            T.jdigveri AS Cuotas_jdigveri, 
            T.JImpCuota AS Cuotas_JImpCuota, 
            T.JIntCuota AS Cuotas_JIntCuota, 
            T.JImpPago AS Cuotas_JImpPago, 
            T.JImpPuni AS Cuotas_JImpPuni, 
            T.JFechUlti AS Cuotas_JFechUlti, 
            T.JFechVenci AS Cuotas_JFechVenci, 
            T.Jtipo AS Cuotas_Jtipo, 
            T.JCantCuota AS Cuotas_JCantCuota, 
            T.JGestion AS Cuotas_JGestion, 
            T.JFechGest AS Cuotas_JFechGest, 
            T.JCarta1 AS Cuotas_JCarta1, 
            T.JFechaC1 AS Cuotas_JFechaC1, 
            T.JCarta2 AS Cuotas_JCarta2, 
            T.JFechaC2 AS Cuotas_JFechaC2, 
            T.JCarta3 AS Cuotas_JCarta3, 
            T.JFechaC3 AS Cuotas_JFechaC3, 
            T.JCarta4 AS Cuotas_JCarta4, 
            T.JFechaC4 AS Cuotas_JFechaC4, 
            T.JBonificado AS Cuotas_JBonificado, 
            T.jnotas AS Cuotas_jnotas, 
            T.JBonicado AS Cuotas_JBonicado, 
            T.TipoBoni AS Cuotas_TipoBoni, 
            T.PorBoni AS Cuotas_PorBoni, 
            T.VaM AS Cuotas_VaM, 
            True AS _from0
        FROM ComerFinanEntities.CuotasANT AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.CuotasANT.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CuotasANT
        [ComerFinanModel.CuotasANT](T1.CuotasANT_JComercio, T1.CuotasANT_JCredito, T1.CuotasANT_JNumCuota, T1.CuotasANT_jdigveri, T1.CuotasANT_JImpCuota, T1.CuotasANT_JIntCuota, T1.CuotasANT_JImpPago, T1.CuotasANT_JImpPuni, T1.CuotasANT_JFechUlti, T1.CuotasANT_JFechVenci, T1.CuotasANT_Jtipo, T1.CuotasANT_JCantCuota, T1.CuotasANT_JGestion, T1.CuotasANT_JFechGest, T1.CuotasANT_JCarta1, T1.CuotasANT_JFechaC1, T1.CuotasANT_JCarta2, T1.CuotasANT_JFechaC2, T1.CuotasANT_JCarta3, T1.CuotasANT_JFechaC3, T1.CuotasANT_JCarta4, T1.CuotasANT_JFechaC4, T1.CuotasANT_JBonificado, T1.CuotasANT_jnotas, T1.CuotasANT_JBonicado, T1.CuotasANT_TipoBoni, T1.CuotasANT_PorBoni, T1.CuotasANT_VaM)
    FROM (
        SELECT 
            T.JComercio AS CuotasANT_JComercio, 
            T.JCredito AS CuotasANT_JCredito, 
            T.JNumCuota AS CuotasANT_JNumCuota, 
            T.jdigveri AS CuotasANT_jdigveri, 
            T.JImpCuota AS CuotasANT_JImpCuota, 
            T.JIntCuota AS CuotasANT_JIntCuota, 
            T.JImpPago AS CuotasANT_JImpPago, 
            T.JImpPuni AS CuotasANT_JImpPuni, 
            T.JFechUlti AS CuotasANT_JFechUlti, 
            T.JFechVenci AS CuotasANT_JFechVenci, 
            T.Jtipo AS CuotasANT_Jtipo, 
            T.JCantCuota AS CuotasANT_JCantCuota, 
            T.JGestion AS CuotasANT_JGestion, 
            T.JFechGest AS CuotasANT_JFechGest, 
            T.JCarta1 AS CuotasANT_JCarta1, 
            T.JFechaC1 AS CuotasANT_JFechaC1, 
            T.JCarta2 AS CuotasANT_JCarta2, 
            T.JFechaC2 AS CuotasANT_JFechaC2, 
            T.JCarta3 AS CuotasANT_JCarta3, 
            T.JFechaC3 AS CuotasANT_JFechaC3, 
            T.JCarta4 AS CuotasANT_JCarta4, 
            T.JFechaC4 AS CuotasANT_JFechaC4, 
            T.JBonificado AS CuotasANT_JBonificado, 
            T.jnotas AS CuotasANT_jnotas, 
            T.JBonicado AS CuotasANT_JBonicado, 
            T.TipoBoni AS CuotasANT_TipoBoni, 
            T.PorBoni AS CuotasANT_PorBoni, 
            T.VaM AS CuotasANT_VaM, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Cuotas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Notas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Notas
        [ComerFinanModel.Store.Notas](T1.Notas_CodNota, T1.Notas_Numero, T1.Notas_Valor, T1.Notas_FechaNota, T1.Notas_Causa, T1.Notas_NroOrden, T1.Notas_FechaOrden, T1.Notas_Comercio, T1.Notas_Credito, T1.Notas_NumCuota, T1.Notas_Minuta, T1.Notas_NumExtra, T1.Notas_FechaMin, T1.Notas_Tasa, T1.Notas_Fecha, T1.Notas_Hora, T1.Notas_Usuario, T1.Notas_Tipo, T1.Notas_Aplicado, T1.Notas_Autorizo, T1.Notas_FechaAut, T1.Notas_Confeccion, T1.Notas_PorImporte, T1.Notas_Conformado, T1.Notas_VaM)
    FROM (
        SELECT 
            T.CodNota AS Notas_CodNota, 
            T.Numero AS Notas_Numero, 
            T.Valor AS Notas_Valor, 
            T.FechaNota AS Notas_FechaNota, 
            T.Causa AS Notas_Causa, 
            T.NroOrden AS Notas_NroOrden, 
            T.FechaOrden AS Notas_FechaOrden, 
            T.Comercio AS Notas_Comercio, 
            T.Credito AS Notas_Credito, 
            T.NumCuota AS Notas_NumCuota, 
            T.Minuta AS Notas_Minuta, 
            T.NumExtra AS Notas_NumExtra, 
            T.FechaMin AS Notas_FechaMin, 
            T.Tasa AS Notas_Tasa, 
            T.Fecha AS Notas_Fecha, 
            T.Hora AS Notas_Hora, 
            T.Usuario AS Notas_Usuario, 
            T.Tipo AS Notas_Tipo, 
            T.Aplicado AS Notas_Aplicado, 
            T.Autorizo AS Notas_Autorizo, 
            T.FechaAut AS Notas_FechaAut, 
            T.Confeccion AS Notas_Confeccion, 
            T.PorImporte AS Notas_PorImporte, 
            T.Conformado AS Notas_Conformado, 
            T.VaM AS Notas_VaM, 
            True AS _from0
        FROM ComerFinanEntities.Notas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.Notas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Notas
        [ComerFinanModel.Notas](T1.Notas_CodNota, T1.Notas_Numero, T1.Notas_Valor, T1.Notas_FechaNota, T1.Notas_Causa, T1.Notas_NroOrden, T1.Notas_FechaOrden, T1.Notas_Comercio, T1.Notas_Credito, T1.Notas_NumCuota, T1.Notas_Minuta, T1.Notas_NumExtra, T1.Notas_FechaMin, T1.Notas_Tasa, T1.Notas_Fecha, T1.Notas_Hora, T1.Notas_Usuario, T1.Notas_Tipo, T1.Notas_Aplicado, T1.Notas_Autorizo, T1.Notas_FechaAut, T1.Notas_Confeccion, T1.Notas_PorImporte, T1.Notas_Conformado, T1.Notas_VaM)
    FROM (
        SELECT 
            T.CodNota AS Notas_CodNota, 
            T.Numero AS Notas_Numero, 
            T.Valor AS Notas_Valor, 
            T.FechaNota AS Notas_FechaNota, 
            T.Causa AS Notas_Causa, 
            T.NroOrden AS Notas_NroOrden, 
            T.FechaOrden AS Notas_FechaOrden, 
            T.Comercio AS Notas_Comercio, 
            T.Credito AS Notas_Credito, 
            T.NumCuota AS Notas_NumCuota, 
            T.Minuta AS Notas_Minuta, 
            T.NumExtra AS Notas_NumExtra, 
            T.FechaMin AS Notas_FechaMin, 
            T.Tasa AS Notas_Tasa, 
            T.Fecha AS Notas_Fecha, 
            T.Hora AS Notas_Hora, 
            T.Usuario AS Notas_Usuario, 
            T.Tipo AS Notas_Tipo, 
            T.Aplicado AS Notas_Aplicado, 
            T.Autorizo AS Notas_Autorizo, 
            T.FechaAut AS Notas_FechaAut, 
            T.Confeccion AS Notas_Confeccion, 
            T.PorImporte AS Notas_PorImporte, 
            T.Conformado AS Notas_Conformado, 
            T.VaM AS Notas_VaM, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Notas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.RefiBaja.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RefiBaja
        [ComerFinanModel.Store.RefiBaja](T1.RefiBaja_KComercio, T1.RefiBaja_KCredito, T1.RefiBaja_KCreditoAnt, T1.RefiBaja_KLote, T1.RefiBaja_KFechaLote, T1.RefiBaja_Usuario, T1.RefiBaja_KDocumento, T1.RefiBaja_KCodDocu, T1.RefiBaja_KValorNom, T1.RefiBaja_KValorCuota, T1.RefiBaja_KFechSoli, T1.RefiBaja_KFechCorte, T1.RefiBaja_KFechPrese, T1.RefiBaja_KFechProce, T1.RefiBaja_KOrden, T1.RefiBaja_KInteresImp, T1.RefiBaja_KGastoImp, T1.RefiBaja_KComisionImp, T1.RefiBaja_KAvalado, T1.RefiBaja_KCancelado, T1.RefiBaja_KGarante1, T1.RefiBaja_KCodDocuG1, T1.RefiBaja_KGarante2, T1.RefiBaja_KCodDocuG2, T1.RefiBaja_KGarante3, T1.RefiBaja_KCodDocuG3, T1.RefiBaja_KVtopp, T1.RefiBaja_KCodPlan, T1.RefiBaja_KTipCuota, T1.RefiBaja_KCuotas, T1.RefiBaja_KTasa, T1.RefiBaja_KGasto, T1.RefiBaja_KPeriodi, T1.RefiBaja_KRetencion, T1.RefiBaja_KPremiun, T1.RefiBaja_KEfectivo, T1.RefiBaja_KBonifica, T1.RefiBaja_KPlazo, T1.RefiBaja_KComision, T1.RefiBaja_KVenci, T1.RefiBaja_KCorte1, T1.RefiBaja_KCorte2, T1.RefiBaja_KVenDia1, T1.RefiBaja_KVenDia2, T1.RefiBaja_KVenDia3, T1.RefiBaja_KNotas, T1.RefiBaja_KAbogado, T1.RefiBaja_FechaAbo, T1.RefiBaja_Carta1, T1.RefiBaja_FechaC1, T1.RefiBaja_Carta2, T1.RefiBaja_FechaC2, T1.RefiBaja_Carta3, T1.RefiBaja_FechaC3, T1.RefiBaja_Carta4, T1.RefiBaja_FechaC4, T1.RefiBaja_KBaja)
    FROM (
        SELECT 
            T.KComercio AS RefiBaja_KComercio, 
            T.KCredito AS RefiBaja_KCredito, 
            T.KCreditoAnt AS RefiBaja_KCreditoAnt, 
            T.KLote AS RefiBaja_KLote, 
            T.KFechaLote AS RefiBaja_KFechaLote, 
            T.Usuario AS RefiBaja_Usuario, 
            T.KDocumento AS RefiBaja_KDocumento, 
            T.KCodDocu AS RefiBaja_KCodDocu, 
            T.KValorNom AS RefiBaja_KValorNom, 
            T.KValorCuota AS RefiBaja_KValorCuota, 
            T.KFechSoli AS RefiBaja_KFechSoli, 
            T.KFechCorte AS RefiBaja_KFechCorte, 
            T.KFechPrese AS RefiBaja_KFechPrese, 
            T.KFechProce AS RefiBaja_KFechProce, 
            T.KOrden AS RefiBaja_KOrden, 
            T.KInteresImp AS RefiBaja_KInteresImp, 
            T.KGastoImp AS RefiBaja_KGastoImp, 
            T.KComisionImp AS RefiBaja_KComisionImp, 
            T.KAvalado AS RefiBaja_KAvalado, 
            T.KCancelado AS RefiBaja_KCancelado, 
            T.KGarante1 AS RefiBaja_KGarante1, 
            T.KCodDocuG1 AS RefiBaja_KCodDocuG1, 
            T.KGarante2 AS RefiBaja_KGarante2, 
            T.KCodDocuG2 AS RefiBaja_KCodDocuG2, 
            T.KGarante3 AS RefiBaja_KGarante3, 
            T.KCodDocuG3 AS RefiBaja_KCodDocuG3, 
            T.KVtopp AS RefiBaja_KVtopp, 
            T.KCodPlan AS RefiBaja_KCodPlan, 
            T.KTipCuota AS RefiBaja_KTipCuota, 
            T.KCuotas AS RefiBaja_KCuotas, 
            T.KTasa AS RefiBaja_KTasa, 
            T.KGasto AS RefiBaja_KGasto, 
            T.KPeriodi AS RefiBaja_KPeriodi, 
            T.KRetencion AS RefiBaja_KRetencion, 
            T.KPremiun AS RefiBaja_KPremiun, 
            T.KEfectivo AS RefiBaja_KEfectivo, 
            T.KBonifica AS RefiBaja_KBonifica, 
            T.KPlazo AS RefiBaja_KPlazo, 
            T.KComision AS RefiBaja_KComision, 
            T.KVenci AS RefiBaja_KVenci, 
            T.KCorte1 AS RefiBaja_KCorte1, 
            T.KCorte2 AS RefiBaja_KCorte2, 
            T.KVenDia1 AS RefiBaja_KVenDia1, 
            T.KVenDia2 AS RefiBaja_KVenDia2, 
            T.KVenDia3 AS RefiBaja_KVenDia3, 
            T.KNotas AS RefiBaja_KNotas, 
            T.KAbogado AS RefiBaja_KAbogado, 
            T.FechaAbo AS RefiBaja_FechaAbo, 
            T.Carta1 AS RefiBaja_Carta1, 
            T.FechaC1 AS RefiBaja_FechaC1, 
            T.Carta2 AS RefiBaja_Carta2, 
            T.FechaC2 AS RefiBaja_FechaC2, 
            T.Carta3 AS RefiBaja_Carta3, 
            T.FechaC3 AS RefiBaja_FechaC3, 
            T.Carta4 AS RefiBaja_Carta4, 
            T.FechaC4 AS RefiBaja_FechaC4, 
            T.KBaja AS RefiBaja_KBaja, 
            True AS _from0
        FROM ComerFinanEntities.RefiBaja AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.RefiBaja.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RefiBaja
        [ComerFinanModel.RefiBaja](T1.RefiBaja_KComercio, T1.RefiBaja_KCredito, T1.RefiBaja_KCreditoAnt, T1.RefiBaja_KLote, T1.RefiBaja_KFechaLote, T1.RefiBaja_Usuario, T1.RefiBaja_KDocumento, T1.RefiBaja_KCodDocu, T1.RefiBaja_KValorNom, T1.RefiBaja_KValorCuota, T1.RefiBaja_KFechSoli, T1.RefiBaja_KFechCorte, T1.RefiBaja_KFechPrese, T1.RefiBaja_KFechProce, T1.RefiBaja_KOrden, T1.RefiBaja_KInteresImp, T1.RefiBaja_KGastoImp, T1.RefiBaja_KComisionImp, T1.RefiBaja_KAvalado, T1.RefiBaja_KCancelado, T1.RefiBaja_KGarante1, T1.RefiBaja_KCodDocuG1, T1.RefiBaja_KGarante2, T1.RefiBaja_KCodDocuG2, T1.RefiBaja_KGarante3, T1.RefiBaja_KCodDocuG3, T1.RefiBaja_KVtopp, T1.RefiBaja_KCodPlan, T1.RefiBaja_KTipCuota, T1.RefiBaja_KCuotas, T1.RefiBaja_KTasa, T1.RefiBaja_KGasto, T1.RefiBaja_KPeriodi, T1.RefiBaja_KRetencion, T1.RefiBaja_KPremiun, T1.RefiBaja_KEfectivo, T1.RefiBaja_KBonifica, T1.RefiBaja_KPlazo, T1.RefiBaja_KComision, T1.RefiBaja_KVenci, T1.RefiBaja_KCorte1, T1.RefiBaja_KCorte2, T1.RefiBaja_KVenDia1, T1.RefiBaja_KVenDia2, T1.RefiBaja_KVenDia3, T1.RefiBaja_KNotas, T1.RefiBaja_KAbogado, T1.RefiBaja_FechaAbo, T1.RefiBaja_Carta1, T1.RefiBaja_FechaC1, T1.RefiBaja_Carta2, T1.RefiBaja_FechaC2, T1.RefiBaja_Carta3, T1.RefiBaja_FechaC3, T1.RefiBaja_Carta4, T1.RefiBaja_FechaC4, T1.RefiBaja_KBaja)
    FROM (
        SELECT 
            T.KComercio AS RefiBaja_KComercio, 
            T.KCredito AS RefiBaja_KCredito, 
            T.KCreditoAnt AS RefiBaja_KCreditoAnt, 
            T.KLote AS RefiBaja_KLote, 
            T.KFechaLote AS RefiBaja_KFechaLote, 
            T.Usuario AS RefiBaja_Usuario, 
            T.KDocumento AS RefiBaja_KDocumento, 
            T.KCodDocu AS RefiBaja_KCodDocu, 
            T.KValorNom AS RefiBaja_KValorNom, 
            T.KValorCuota AS RefiBaja_KValorCuota, 
            T.KFechSoli AS RefiBaja_KFechSoli, 
            T.KFechCorte AS RefiBaja_KFechCorte, 
            T.KFechPrese AS RefiBaja_KFechPrese, 
            T.KFechProce AS RefiBaja_KFechProce, 
            T.KOrden AS RefiBaja_KOrden, 
            T.KInteresImp AS RefiBaja_KInteresImp, 
            T.KGastoImp AS RefiBaja_KGastoImp, 
            T.KComisionImp AS RefiBaja_KComisionImp, 
            T.KAvalado AS RefiBaja_KAvalado, 
            T.KCancelado AS RefiBaja_KCancelado, 
            T.KGarante1 AS RefiBaja_KGarante1, 
            T.KCodDocuG1 AS RefiBaja_KCodDocuG1, 
            T.KGarante2 AS RefiBaja_KGarante2, 
            T.KCodDocuG2 AS RefiBaja_KCodDocuG2, 
            T.KGarante3 AS RefiBaja_KGarante3, 
            T.KCodDocuG3 AS RefiBaja_KCodDocuG3, 
            T.KVtopp AS RefiBaja_KVtopp, 
            T.KCodPlan AS RefiBaja_KCodPlan, 
            T.KTipCuota AS RefiBaja_KTipCuota, 
            T.KCuotas AS RefiBaja_KCuotas, 
            T.KTasa AS RefiBaja_KTasa, 
            T.KGasto AS RefiBaja_KGasto, 
            T.KPeriodi AS RefiBaja_KPeriodi, 
            T.KRetencion AS RefiBaja_KRetencion, 
            T.KPremiun AS RefiBaja_KPremiun, 
            T.KEfectivo AS RefiBaja_KEfectivo, 
            T.KBonifica AS RefiBaja_KBonifica, 
            T.KPlazo AS RefiBaja_KPlazo, 
            T.KComision AS RefiBaja_KComision, 
            T.KVenci AS RefiBaja_KVenci, 
            T.KCorte1 AS RefiBaja_KCorte1, 
            T.KCorte2 AS RefiBaja_KCorte2, 
            T.KVenDia1 AS RefiBaja_KVenDia1, 
            T.KVenDia2 AS RefiBaja_KVenDia2, 
            T.KVenDia3 AS RefiBaja_KVenDia3, 
            T.KNotas AS RefiBaja_KNotas, 
            T.KAbogado AS RefiBaja_KAbogado, 
            T.FechaAbo AS RefiBaja_FechaAbo, 
            T.Carta1 AS RefiBaja_Carta1, 
            T.FechaC1 AS RefiBaja_FechaC1, 
            T.Carta2 AS RefiBaja_Carta2, 
            T.FechaC2 AS RefiBaja_FechaC2, 
            T.Carta3 AS RefiBaja_Carta3, 
            T.FechaC3 AS RefiBaja_FechaC3, 
            T.Carta4 AS RefiBaja_Carta4, 
            T.FechaC4 AS RefiBaja_FechaC4, 
            T.KBaja AS RefiBaja_KBaja, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.RefiBaja AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Reficobra.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Reficobra
        [ComerFinanModel.Store.Reficobra](T1.Reficobra_AComercio, T1.Reficobra_ACredito, T1.Reficobra_ANumCuota, T1.Reficobra_ANumCob, T1.Reficobra_ADigVeri, T1.Reficobra_AImpPago, T1.Reficobra_AImpPuni, T1.Reficobra_AImpInte, T1.Reficobra_AFechaPago, T1.Reficobra_AHoraPago, T1.Reficobra_APuniCalc, T1.Reficobra_ALote, T1.Reficobra_AFechLote, T1.Reficobra_AFechPro, T1.Reficobra_APago, T1.Reficobra_AImpPagoAnt, T1.Reficobra_AFechPagoAnt, T1.Reficobra_AImpPuniAnt, T1.Reficobra_APagoRev, T1.Reficobra_AFechaRev, T1.Reficobra_ABonificado, T1.Reficobra_ADeta, T1.Reficobra_AGestion, T1.Reficobra_Usuario, T1.Reficobra_AFechVenci)
    FROM (
        SELECT 
            T.AComercio AS Reficobra_AComercio, 
            T.ACredito AS Reficobra_ACredito, 
            T.ANumCuota AS Reficobra_ANumCuota, 
            T.ANumCob AS Reficobra_ANumCob, 
            T.ADigVeri AS Reficobra_ADigVeri, 
            T.AImpPago AS Reficobra_AImpPago, 
            T.AImpPuni AS Reficobra_AImpPuni, 
            T.AImpInte AS Reficobra_AImpInte, 
            T.AFechaPago AS Reficobra_AFechaPago, 
            T.AHoraPago AS Reficobra_AHoraPago, 
            T.APuniCalc AS Reficobra_APuniCalc, 
            T.ALote AS Reficobra_ALote, 
            T.AFechLote AS Reficobra_AFechLote, 
            T.AFechPro AS Reficobra_AFechPro, 
            T.APago AS Reficobra_APago, 
            T.AImpPagoAnt AS Reficobra_AImpPagoAnt, 
            T.AFechPagoAnt AS Reficobra_AFechPagoAnt, 
            T.AImpPuniAnt AS Reficobra_AImpPuniAnt, 
            T.APagoRev AS Reficobra_APagoRev, 
            T.AFechaRev AS Reficobra_AFechaRev, 
            T.ABonificado AS Reficobra_ABonificado, 
            T.ADeta AS Reficobra_ADeta, 
            T.AGestion AS Reficobra_AGestion, 
            T.Usuario AS Reficobra_Usuario, 
            T.AFechVenci AS Reficobra_AFechVenci, 
            True AS _from0
        FROM ComerFinanEntities.RefiCobra AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.RefiCobra.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RefiCobra
        [ComerFinanModel.RefiCobra](T1.RefiCobra_AComercio, T1.RefiCobra_ACredito, T1.RefiCobra_ANumCuota, T1.RefiCobra_ANumCob, T1.RefiCobra_ADigVeri, T1.RefiCobra_AImpPago, T1.RefiCobra_AImpPuni, T1.RefiCobra_AImpInte, T1.RefiCobra_AFechaPago, T1.RefiCobra_AHoraPago, T1.RefiCobra_APuniCalc, T1.RefiCobra_ALote, T1.RefiCobra_AFechLote, T1.RefiCobra_AFechPro, T1.RefiCobra_APago, T1.RefiCobra_AImpPagoAnt, T1.RefiCobra_AFechPagoAnt, T1.RefiCobra_AImpPuniAnt, T1.RefiCobra_APagoRev, T1.RefiCobra_AFechaRev, T1.RefiCobra_ABonificado, T1.RefiCobra_ADeta, T1.RefiCobra_AGestion, T1.RefiCobra_Usuario, T1.RefiCobra_AFechVenci)
    FROM (
        SELECT 
            T.AComercio AS RefiCobra_AComercio, 
            T.ACredito AS RefiCobra_ACredito, 
            T.ANumCuota AS RefiCobra_ANumCuota, 
            T.ANumCob AS RefiCobra_ANumCob, 
            T.ADigVeri AS RefiCobra_ADigVeri, 
            T.AImpPago AS RefiCobra_AImpPago, 
            T.AImpPuni AS RefiCobra_AImpPuni, 
            T.AImpInte AS RefiCobra_AImpInte, 
            T.AFechaPago AS RefiCobra_AFechaPago, 
            T.AHoraPago AS RefiCobra_AHoraPago, 
            T.APuniCalc AS RefiCobra_APuniCalc, 
            T.ALote AS RefiCobra_ALote, 
            T.AFechLote AS RefiCobra_AFechLote, 
            T.AFechPro AS RefiCobra_AFechPro, 
            T.APago AS RefiCobra_APago, 
            T.AImpPagoAnt AS RefiCobra_AImpPagoAnt, 
            T.AFechPagoAnt AS RefiCobra_AFechPagoAnt, 
            T.AImpPuniAnt AS RefiCobra_AImpPuniAnt, 
            T.APagoRev AS RefiCobra_APagoRev, 
            T.AFechaRev AS RefiCobra_AFechaRev, 
            T.ABonificado AS RefiCobra_ABonificado, 
            T.ADeta AS RefiCobra_ADeta, 
            T.AGestion AS RefiCobra_AGestion, 
            T.Usuario AS RefiCobra_Usuario, 
            T.AFechVenci AS RefiCobra_AFechVenci, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Reficobra AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.RefiCuotas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RefiCuotas
        [ComerFinanModel.Store.RefiCuotas](T1.RefiCuotas_JComercio, T1.RefiCuotas_JCredito, T1.RefiCuotas_JNumCuota, T1.RefiCuotas_JDigVeri, T1.RefiCuotas_JImpCuota, T1.RefiCuotas_JIntCuota, T1.RefiCuotas_JImpPago, T1.RefiCuotas_JImpPuni, T1.RefiCuotas_JFechUlti, T1.RefiCuotas_JFechVenci, T1.RefiCuotas_Jtipo, T1.RefiCuotas_JCantCuota, T1.RefiCuotas_JGestion, T1.RefiCuotas_JFechGest)
    FROM (
        SELECT 
            T.JComercio AS RefiCuotas_JComercio, 
            T.JCredito AS RefiCuotas_JCredito, 
            T.JNumCuota AS RefiCuotas_JNumCuota, 
            T.JDigVeri AS RefiCuotas_JDigVeri, 
            T.JImpCuota AS RefiCuotas_JImpCuota, 
            T.JIntCuota AS RefiCuotas_JIntCuota, 
            T.JImpPago AS RefiCuotas_JImpPago, 
            T.JImpPuni AS RefiCuotas_JImpPuni, 
            T.JFechUlti AS RefiCuotas_JFechUlti, 
            T.JFechVenci AS RefiCuotas_JFechVenci, 
            T.Jtipo AS RefiCuotas_Jtipo, 
            T.JCantCuota AS RefiCuotas_JCantCuota, 
            T.JGestion AS RefiCuotas_JGestion, 
            T.JFechGest AS RefiCuotas_JFechGest, 
            True AS _from0
        FROM ComerFinanEntities.RefiCuotas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.RefiCuotas.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RefiCuotas
        [ComerFinanModel.RefiCuotas](T1.RefiCuotas_JComercio, T1.RefiCuotas_JCredito, T1.RefiCuotas_JNumCuota, T1.RefiCuotas_JDigVeri, T1.RefiCuotas_JImpCuota, T1.RefiCuotas_JIntCuota, T1.RefiCuotas_JImpPago, T1.RefiCuotas_JImpPuni, T1.RefiCuotas_JFechUlti, T1.RefiCuotas_JFechVenci, T1.RefiCuotas_Jtipo, T1.RefiCuotas_JCantCuota, T1.RefiCuotas_JGestion, T1.RefiCuotas_JFechGest)
    FROM (
        SELECT 
            T.JComercio AS RefiCuotas_JComercio, 
            T.JCredito AS RefiCuotas_JCredito, 
            T.JNumCuota AS RefiCuotas_JNumCuota, 
            T.JDigVeri AS RefiCuotas_JDigVeri, 
            T.JImpCuota AS RefiCuotas_JImpCuota, 
            T.JIntCuota AS RefiCuotas_JIntCuota, 
            T.JImpPago AS RefiCuotas_JImpPago, 
            T.JImpPuni AS RefiCuotas_JImpPuni, 
            T.JFechUlti AS RefiCuotas_JFechUlti, 
            T.JFechVenci AS RefiCuotas_JFechVenci, 
            T.Jtipo AS RefiCuotas_Jtipo, 
            T.JCantCuota AS RefiCuotas_JCantCuota, 
            T.JGestion AS RefiCuotas_JGestion, 
            T.JFechGest AS RefiCuotas_JFechGest, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.RefiCuotas AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanModelStoreContainer.Refinan.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Refinan
        [ComerFinanModel.Store.Refinan](T1.Refinan_KComercio, T1.Refinan_KCredito, T1.Refinan_KCreditoAnt, T1.Refinan_KDocumento, T1.Refinan_KCodDocu, T1.Refinan_KValorNom, T1.Refinan_KValorCuota, T1.Refinan_KFechSoli, T1.Refinan_KFechCorte, T1.Refinan_KFechPrese, T1.Refinan_KFechProce, T1.Refinan_KLote, T1.Refinan_KFechaLote, T1.Refinan_KOrden, T1.Refinan_KInteresImp, T1.Refinan_KGastoImp, T1.Refinan_KComisionImp, T1.Refinan_KAvalado, T1.Refinan_KCancelado, T1.Refinan_KGarante1, T1.Refinan_KCodDocuG1, T1.Refinan_KGarante2, T1.Refinan_KCodDocuG2, T1.Refinan_KGarante3, T1.Refinan_KCodDocuG3, T1.Refinan_KVtopp, T1.Refinan_KCodPlan, T1.Refinan_KTipCuota, T1.Refinan_KCuotas, T1.Refinan_KTasa, T1.Refinan_KGasto, T1.Refinan_KPeriodi, T1.Refinan_KRetencion, T1.Refinan_KPremiun, T1.Refinan_KEfectivo, T1.Refinan_KBonifica, T1.Refinan_KPlazo, T1.Refinan_KComision, T1.Refinan_KVenci, T1.Refinan_KCorte1, T1.Refinan_KCorte2, T1.Refinan_KVenDia1, T1.Refinan_KVenDia2, T1.Refinan_KVenDia3, T1.Refinan_KNotas, T1.Refinan_KAbogado, T1.Refinan_FechaAbo, T1.Refinan_Carta1, T1.Refinan_FechaC1, T1.Refinan_Carta2, T1.Refinan_FechaC2, T1.Refinan_Carta3, T1.Refinan_FechaC3, T1.Refinan_Carta4, T1.Refinan_FechaC4, T1.Refinan_KBaja, T1.Refinan_Usuario)
    FROM (
        SELECT 
            T.KComercio AS Refinan_KComercio, 
            T.KCredito AS Refinan_KCredito, 
            T.KCreditoAnt AS Refinan_KCreditoAnt, 
            T.KDocumento AS Refinan_KDocumento, 
            T.KCodDocu AS Refinan_KCodDocu, 
            T.KValorNom AS Refinan_KValorNom, 
            T.KValorCuota AS Refinan_KValorCuota, 
            T.KFechSoli AS Refinan_KFechSoli, 
            T.KFechCorte AS Refinan_KFechCorte, 
            T.KFechPrese AS Refinan_KFechPrese, 
            T.KFechProce AS Refinan_KFechProce, 
            T.KLote AS Refinan_KLote, 
            T.KFechaLote AS Refinan_KFechaLote, 
            T.KOrden AS Refinan_KOrden, 
            T.KInteresImp AS Refinan_KInteresImp, 
            T.KGastoImp AS Refinan_KGastoImp, 
            T.KComisionImp AS Refinan_KComisionImp, 
            T.KAvalado AS Refinan_KAvalado, 
            T.KCancelado AS Refinan_KCancelado, 
            T.KGarante1 AS Refinan_KGarante1, 
            T.KCodDocuG1 AS Refinan_KCodDocuG1, 
            T.KGarante2 AS Refinan_KGarante2, 
            T.KCodDocuG2 AS Refinan_KCodDocuG2, 
            T.KGarante3 AS Refinan_KGarante3, 
            T.KCodDocuG3 AS Refinan_KCodDocuG3, 
            T.KVtopp AS Refinan_KVtopp, 
            T.KCodPlan AS Refinan_KCodPlan, 
            T.KTipCuota AS Refinan_KTipCuota, 
            T.KCuotas AS Refinan_KCuotas, 
            T.KTasa AS Refinan_KTasa, 
            T.KGasto AS Refinan_KGasto, 
            T.KPeriodi AS Refinan_KPeriodi, 
            T.KRetencion AS Refinan_KRetencion, 
            T.KPremiun AS Refinan_KPremiun, 
            T.KEfectivo AS Refinan_KEfectivo, 
            T.KBonifica AS Refinan_KBonifica, 
            T.KPlazo AS Refinan_KPlazo, 
            T.KComision AS Refinan_KComision, 
            T.KVenci AS Refinan_KVenci, 
            T.KCorte1 AS Refinan_KCorte1, 
            T.KCorte2 AS Refinan_KCorte2, 
            T.KVenDia1 AS Refinan_KVenDia1, 
            T.KVenDia2 AS Refinan_KVenDia2, 
            T.KVenDia3 AS Refinan_KVenDia3, 
            T.KNotas AS Refinan_KNotas, 
            T.KAbogado AS Refinan_KAbogado, 
            T.FechaAbo AS Refinan_FechaAbo, 
            T.Carta1 AS Refinan_Carta1, 
            T.FechaC1 AS Refinan_FechaC1, 
            T.Carta2 AS Refinan_Carta2, 
            T.FechaC2 AS Refinan_FechaC2, 
            T.Carta3 AS Refinan_Carta3, 
            T.FechaC3 AS Refinan_FechaC3, 
            T.Carta4 AS Refinan_Carta4, 
            T.FechaC4 AS Refinan_FechaC4, 
            T.KBaja AS Refinan_KBaja, 
            T.Usuario AS Refinan_Usuario, 
            True AS _from0
        FROM ComerFinanEntities.Refinan AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for ComerFinanEntities.Refinan.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Refinan
        [ComerFinanModel.Refinan](T1.Refinan_KComercio, T1.Refinan_KCredito, T1.Refinan_KCreditoAnt, T1.Refinan_KDocumento, T1.Refinan_KCodDocu, T1.Refinan_KValorNom, T1.Refinan_KValorCuota, T1.Refinan_KFechSoli, T1.Refinan_KFechCorte, T1.Refinan_KFechPrese, T1.Refinan_KFechProce, T1.Refinan_KLote, T1.Refinan_KFechaLote, T1.Refinan_KOrden, T1.Refinan_KInteresImp, T1.Refinan_KGastoImp, T1.Refinan_KComisionImp, T1.Refinan_KAvalado, T1.Refinan_KCancelado, T1.Refinan_KGarante1, T1.Refinan_KCodDocuG1, T1.Refinan_KGarante2, T1.Refinan_KCodDocuG2, T1.Refinan_KGarante3, T1.Refinan_KCodDocuG3, T1.Refinan_KVtopp, T1.Refinan_KCodPlan, T1.Refinan_KTipCuota, T1.Refinan_KCuotas, T1.Refinan_KTasa, T1.Refinan_KGasto, T1.Refinan_KPeriodi, T1.Refinan_KRetencion, T1.Refinan_KPremiun, T1.Refinan_KEfectivo, T1.Refinan_KBonifica, T1.Refinan_KPlazo, T1.Refinan_KComision, T1.Refinan_KVenci, T1.Refinan_KCorte1, T1.Refinan_KCorte2, T1.Refinan_KVenDia1, T1.Refinan_KVenDia2, T1.Refinan_KVenDia3, T1.Refinan_KNotas, T1.Refinan_KAbogado, T1.Refinan_FechaAbo, T1.Refinan_Carta1, T1.Refinan_FechaC1, T1.Refinan_Carta2, T1.Refinan_FechaC2, T1.Refinan_Carta3, T1.Refinan_FechaC3, T1.Refinan_Carta4, T1.Refinan_FechaC4, T1.Refinan_KBaja, T1.Refinan_Usuario)
    FROM (
        SELECT 
            T.KComercio AS Refinan_KComercio, 
            T.KCredito AS Refinan_KCredito, 
            T.KCreditoAnt AS Refinan_KCreditoAnt, 
            T.KDocumento AS Refinan_KDocumento, 
            T.KCodDocu AS Refinan_KCodDocu, 
            T.KValorNom AS Refinan_KValorNom, 
            T.KValorCuota AS Refinan_KValorCuota, 
            T.KFechSoli AS Refinan_KFechSoli, 
            T.KFechCorte AS Refinan_KFechCorte, 
            T.KFechPrese AS Refinan_KFechPrese, 
            T.KFechProce AS Refinan_KFechProce, 
            T.KLote AS Refinan_KLote, 
            T.KFechaLote AS Refinan_KFechaLote, 
            T.KOrden AS Refinan_KOrden, 
            T.KInteresImp AS Refinan_KInteresImp, 
            T.KGastoImp AS Refinan_KGastoImp, 
            T.KComisionImp AS Refinan_KComisionImp, 
            T.KAvalado AS Refinan_KAvalado, 
            T.KCancelado AS Refinan_KCancelado, 
            T.KGarante1 AS Refinan_KGarante1, 
            T.KCodDocuG1 AS Refinan_KCodDocuG1, 
            T.KGarante2 AS Refinan_KGarante2, 
            T.KCodDocuG2 AS Refinan_KCodDocuG2, 
            T.KGarante3 AS Refinan_KGarante3, 
            T.KCodDocuG3 AS Refinan_KCodDocuG3, 
            T.KVtopp AS Refinan_KVtopp, 
            T.KCodPlan AS Refinan_KCodPlan, 
            T.KTipCuota AS Refinan_KTipCuota, 
            T.KCuotas AS Refinan_KCuotas, 
            T.KTasa AS Refinan_KTasa, 
            T.KGasto AS Refinan_KGasto, 
            T.KPeriodi AS Refinan_KPeriodi, 
            T.KRetencion AS Refinan_KRetencion, 
            T.KPremiun AS Refinan_KPremiun, 
            T.KEfectivo AS Refinan_KEfectivo, 
            T.KBonifica AS Refinan_KBonifica, 
            T.KPlazo AS Refinan_KPlazo, 
            T.KComision AS Refinan_KComision, 
            T.KVenci AS Refinan_KVenci, 
            T.KCorte1 AS Refinan_KCorte1, 
            T.KCorte2 AS Refinan_KCorte2, 
            T.KVenDia1 AS Refinan_KVenDia1, 
            T.KVenDia2 AS Refinan_KVenDia2, 
            T.KVenDia3 AS Refinan_KVenDia3, 
            T.KNotas AS Refinan_KNotas, 
            T.KAbogado AS Refinan_KAbogado, 
            T.FechaAbo AS Refinan_FechaAbo, 
            T.Carta1 AS Refinan_Carta1, 
            T.FechaC1 AS Refinan_FechaC1, 
            T.Carta2 AS Refinan_Carta2, 
            T.FechaC2 AS Refinan_FechaC2, 
            T.Carta3 AS Refinan_Carta3, 
            T.FechaC3 AS Refinan_FechaC3, 
            T.Carta4 AS Refinan_Carta4, 
            T.FechaC4 AS Refinan_FechaC4, 
            T.KBaja AS Refinan_KBaja, 
            T.Usuario AS Refinan_Usuario, 
            True AS _from0
        FROM ComerFinanModelStoreContainer.Refinan AS T
    ) AS T1");
        }
    }
}
