//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditosANT
    {
        public short KComercio { get; set; }
        public int KCredito { get; set; }
        public Nullable<int> KDocumento { get; set; }
        public string KCodDocu { get; set; }
        public Nullable<decimal> KValorNom { get; set; }
        public Nullable<decimal> KValorCuota { get; set; }
        public Nullable<System.DateTime> KFechSoli { get; set; }
        public Nullable<System.DateTime> KFechCorte { get; set; }
        public Nullable<System.DateTime> KFechPrese { get; set; }
        public Nullable<System.DateTime> KFechProce { get; set; }
        public Nullable<int> KLote { get; set; }
        public Nullable<int> KNumExtra { get; set; }
        public Nullable<System.DateTime> KFechaLote { get; set; }
        public Nullable<int> KOrden { get; set; }
        public Nullable<decimal> KInteresImp { get; set; }
        public Nullable<decimal> KGastoImp { get; set; }
        public Nullable<decimal> KComisionImp { get; set; }
        public bool KAvalado { get; set; }
        public bool KCancelado { get; set; }
        public Nullable<int> KGarante1 { get; set; }
        public string KCodDocuG1 { get; set; }
        public Nullable<int> KGarante2 { get; set; }
        public string KCodDocuG2 { get; set; }
        public Nullable<int> KGarante3 { get; set; }
        public string KCodDocuG3 { get; set; }
        public string KVtopp { get; set; }
        public string KCodPlan { get; set; }
        public string KTipCuota { get; set; }
        public Nullable<byte> KCuotas { get; set; }
        public Nullable<float> KTasa { get; set; }
        public Nullable<float> KGasto { get; set; }
        public string KPeriodi { get; set; }
        public string KRetencion { get; set; }
        public string KPremiun { get; set; }
        public bool KEfectivo { get; set; }
        public Nullable<byte> KBonifica { get; set; }
        public Nullable<byte> KPlazo { get; set; }
        public Nullable<float> KComision { get; set; }
        public string KVenci { get; set; }
        public Nullable<byte> KCorte1 { get; set; }
        public Nullable<byte> KCorte2 { get; set; }
        public Nullable<byte> KVenDia1 { get; set; }
        public Nullable<byte> KVenDia2 { get; set; }
        public Nullable<byte> KVenDia3 { get; set; }
        public string KNotas { get; set; }
        public Nullable<short> KAbogado { get; set; }
        public Nullable<System.DateTime> kFechaAbo { get; set; }
        public bool Carta1 { get; set; }
        public Nullable<System.DateTime> FechaC1 { get; set; }
        public bool Carta2 { get; set; }
        public Nullable<System.DateTime> FechaC2 { get; set; }
        public bool Carta3 { get; set; }
        public Nullable<System.DateTime> FechaC3 { get; set; }
        public bool Carta4 { get; set; }
        public Nullable<System.DateTime> FechaC4 { get; set; }
        public bool Refinan { get; set; }
        public bool Veraz { get; set; }
        public string QueAvalo { get; set; }
        public string Usuario { get; set; }
        public string CodAdi { get; set; }
        public Nullable<int> DocuAdi { get; set; }
        public Nullable<System.DateTime> FechaAbo { get; set; }
        public string krmpl { get; set; }
        public string kempl { get; set; }
        public Nullable<int> NroInf { get; set; }
        public string UsuAval { get; set; }
        public string TipoBoni { get; set; }
        public Nullable<decimal> PorBoni { get; set; }
    }
}
