//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotasANT
    {
        public short JComercio { get; set; }
        public int JCredito { get; set; }
        public byte JNumCuota { get; set; }
        public string JDigVeri { get; set; }
        public Nullable<decimal> JImpCuota { get; set; }
        public Nullable<decimal> JIntCuota { get; set; }
        public Nullable<decimal> JImpPago { get; set; }
        public Nullable<decimal> JImpPuni { get; set; }
        public Nullable<System.DateTime> JFechUlti { get; set; }
        public Nullable<System.DateTime> JFechVenci { get; set; }
        public string Jtipo { get; set; }
        public Nullable<byte> JCantCuota { get; set; }
        public Nullable<short> JGestion { get; set; }
        public Nullable<System.DateTime> JFechGest { get; set; }
        public bool JBonificado { get; set; }
        public bool JCarta1 { get; set; }
        public Nullable<System.DateTime> JFechaC1 { get; set; }
        public bool JCarta2 { get; set; }
        public Nullable<System.DateTime> JFechaC2 { get; set; }
        public bool JCarta3 { get; set; }
        public Nullable<System.DateTime> JFechaC3 { get; set; }
        public bool JCarta4 { get; set; }
        public Nullable<System.DateTime> JFechaC4 { get; set; }
        public bool JBonicado { get; set; }
        public string jnotas { get; set; }
        public Nullable<decimal> JDeuda { get; set; }
        public string TipoBoni { get; set; }
        public Nullable<decimal> PorBoni { get; set; }
    }
}
