//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    
    public partial class Entidad
    {
        public string CODENT { get; set; }
        public string NOMENT { get; set; }
        public string DIRENT { get; set; }
        public string TELENT { get; set; }
        public string CODENT2 { get; set; }
    }
}
