//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    
    public partial class MorosoEnCamara
    {
        public string EMPRCA { get; set; }
        public string Estado { get; set; }
        public string EMPRCA2 { get; set; }
        public string Estado2 { get; set; }
        public string EMPRCA3 { get; set; }
        public string Estado3 { get; set; }
        public string Mas { get; set; }
        public string APNOCA { get; set; }
        public Nullable<double> NUDOCA { get; set; }
        public string FinanV { get; set; }
        public string nombreEntidad { get; set; }
    }
}
