//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int CodNota { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> FechaNota { get; set; }
        public string Causa { get; set; }
        public Nullable<int> NroOrden { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<short> Comercio { get; set; }
        public Nullable<int> Credito { get; set; }
        public Nullable<byte> NumCuota { get; set; }
        public Nullable<int> Minuta { get; set; }
        public Nullable<int> NumExtra { get; set; }
        public Nullable<System.DateTime> FechaMin { get; set; }
        public Nullable<int> Tasa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Usuario { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Aplicado { get; set; }
        public string Autorizo { get; set; }
        public Nullable<System.DateTime> FechaAut { get; set; }
        public string Confeccion { get; set; }
        public Nullable<decimal> PorImporte { get; set; }
        public bool Conformado { get; set; }
    }
}
