//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefiCobra
    {
        public short AComercio { get; set; }
        public int ACredito { get; set; }
        public byte ANumCuota { get; set; }
        public Nullable<decimal> AImpPago { get; set; }
        public Nullable<decimal> AImpPuni { get; set; }
        public Nullable<System.DateTime> AFechaPago { get; set; }
        public Nullable<System.DateTime> AHoraPago { get; set; }
        public Nullable<decimal> APuniCalc { get; set; }
        public Nullable<int> ALote { get; set; }
        public Nullable<System.DateTime> AFechLote { get; set; }
        public Nullable<System.DateTime> AFechPro { get; set; }
        public string APago { get; set; }
        public bool APagoRev { get; set; }
        public Nullable<System.DateTime> AFechaRev { get; set; }
        public int ANumCob { get; set; }
        public Nullable<System.DateTime> AFechVenci { get; set; }
        public Nullable<short> AGestion { get; set; }
        public string Usuario { get; set; }
    }
}
