//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iComercio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refinan
    {
        public short KComercio { get; set; }
        public int KCredito { get; set; }
        public int KCreditoAnt { get; set; }
        public Nullable<int> KDocumento { get; set; }
        public string KCodDocu { get; set; }
        public Nullable<decimal> KValorNom { get; set; }
        public Nullable<decimal> KValorCuota { get; set; }
        public Nullable<System.DateTime> KFechSoli { get; set; }
        public Nullable<int> KLote { get; set; }
        public Nullable<System.DateTime> KFechaLote { get; set; }
        public Nullable<decimal> KGastoImp { get; set; }
        public Nullable<decimal> KComisionImp { get; set; }
        public bool KCancelado { get; set; }
        public string KTipCuota { get; set; }
        public Nullable<byte> KCuotas { get; set; }
        public Nullable<float> KTasa { get; set; }
        public Nullable<float> KGasto { get; set; }
        public bool KBaja { get; set; }
        public string Usuario { get; set; }
    }
}
